apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: websiteservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: adminservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

  ---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: superadminservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: superadmin-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50