# Enables the pods in a deployment to be accessible from outside the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: portfolioadmin-svc
spec:
  type: ClusterIP
  selector:
    app: portfolio-admin
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: portfoliowebsite-svc
spec:
  type: ClusterIP
  selector:
    app: portfolio-website
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

