name: ci

on:
  workflow_dispatch: # Allows manual trigger of the workflow
  push:             # Trigger the workflow on push events
    branches:
      - main 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push admin
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/admin-service
          push: true
          tags: physcocode/portfolioadmin:v1.11
      -
        name: Build and push website
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/website-service
          push: true
          tags: physcocode/portfoliowebsite:v1.11
